server:
  port: 8081
  address: localhost

spring:
  application:
    name: SpendyAPI
  config:
    activate:
      on-profile: migration

  datasource:
    url: jdbc:postgresql://c724r43q8jp5nk.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d9ln853h1raaks
    username: ue5gebbvenubtf
    password: p7403a7d132f9c27a80234e8febe4d2624fd57393fbde6c02381ef6b4798f1a2f
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database: postgresql
    open-in-view: false