server:
  port: ${PORT}

spring:
  application:
    name: SpendyAPI
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    open-in-view: false
